config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  # We're only using omniauth for now, so need to add our own signout route
  devise_scope :user do
    delete 'signout(.:format)' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :repos, only: [:index, :show] do
    resources :builds, only: [:index, :show] do
      resources :jobs, controller: :build_jobs, only: :show
    end
  end

  post 'notifications/travis', to: 'notifications#travis'
end

app/models/build.rb
class Build < ActiveRecord::Base
  belongs_to :repo
  has_many :jobs, class_name: "BuildJob", inverse_of: :build, dependent: :destroy
  scope :with_artifacts, -> { includes(jobs: :artifacts).where.not(build_job_artifacts: { id: nil }) }

  def artifacts
    if new_record?
      BuildJobArtifact.none
    else
      BuildJobArtifact.joins(job: :build).where('builds.id' => id)
    end
  end

  scope :failed, -> { where(result: 1) }

  def to_param
    number.to_s
  end

  def short_commit
    commit.to_s[0...7]
  end

  def passed?
    result == 0
  end
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  PER_PAGE = 9

  before_filter :authenticate_user!


  def index
    @repo = Repo.find_by_name!(params[:repo_id])
    @builds = @repo.builds.with_artifacts

    if params[:filter] == 'failed'
      @builds = @builds.failed
    end

    @builds = @builds.
      order('builds.created_at DESC').
      page(params[:page]).
      per(PER_PAGE)

    # Check to see if any of the builds have multiple jobs,
    # otherwise we can hide the jobs column.
    @has_multiple_jobs = @builds.count('build_jobs.id') > @builds.count
  end

  def show
    @build = Build.joins(:repo).where(
      'repos.name' => params[:repo_id],
      'builds.number' => params[:id]
    ).first

    unless @build
      flash[:error] = "Build not found!"
      redirect_to repo_path(params[:repo_id])
    end
  end
end

app/helpers/builds_helper.rb
module BuildsHelper
  def latest_build
    @latest_build ||= Build.order('created_at DESC').first
  end

  def class_for_build_status(build)
    if build.passed?
      'passed'
    else
      if build.status_message == 'Errored'
        'errored'
      else
        'failed'
      end
    end
  end

  def class_for_build_job_status(build_job)
    build_job.passed? ? 'passed' : 'failed'
  end

  def class_for_artifact_status(artifact)
    case artifact.status
    when 'changed'
      'changed'
    when 'new'
      'new'
    else
      ''
    end
  end
end

app/views/builds/index.html.haml
.row
  .large-10.large-offset-1.columns
    .header
      %h3
        = @repo.path
        - if params[:filter] == 'failed'
          &mdash; Failed Builds

      - if params[:filter] != 'failed'
        = link_to "Only Failed Builds", repo_builds_path(@repo, filter: :failed), class: 'builds_filter'
      - else
        = link_to "Show All Builds", repo_builds_path(@repo, filter: :all), class: 'builds_filter'

    %table.builds
      %thead
        %tr
          %th
            %span.column-label # Build
          %th
            %span.travis-icon
            %span.column-label Status
          - if @has_multiple_jobs
            %th.build_jobs
              <i class='fi-results'></i>
              %span.column-label Jobs
          %th.screenshots
            <i class="fi-photo"></i>
            %span.column-label Screens
          %th.commit
            <i class='fi-social-github'></i>
            %span.column-label Commit
          %th.branch
            <i class='fi-social-github'></i>
            %span.column-label Branch
          %th.build_date
            <i class='fi-clock'></i>
            %span.column-label When

      %tbody
        - @builds.each do |build|
          %tr.build_row
            %td{class: 'build_status ' << class_for_build_status(build) }
              .build_job
                = link_to "##{build.number}", repo_build_path(@repo, build)

            %td{class: 'build_status ' << class_for_build_status(build) }
              .build_status_message
                = link_to build.status_message, build.build_url
              .build_status_icon.hide
                - if build.passed?
                  <i class="fi-check"></i>
                - else
                  <i class="fi-x"></i>

            - if @has_multiple_jobs
              %td.build_jobs
                - build.jobs.each do |job|
                  .build_job{class: 'build_status ' << class_for_build_job_status(job) }
                    <a href="#{repo_build_job_path(@repo, build, job)}">
                    \##{job.travis_build_number}

                    %span.artifacts_count
                      &mdash;
                      <i class="fi-photo"></i>
                      = job.artifacts.count
                    </a>

            %td.screenshots
              = link_to "#{build.artifacts.count},", repo_build_url(@repo, build), title: 'Total'
              = link_to build.artifacts.all_changes.count, repo_build_url(@repo, build, changed: 1), class: 'changed', title: "Changed"

            %td.commit
              = link_to build.short_commit, build.compare_url
            %td.commit-mobile.hide
              = link_to "<i class='fi-social-github'></i>".html_safe, build.compare_url

            %td.branch= build.branch
            %td.build_date
              = time_ago_in_words build.created_at
              ago



    = paginate @builds

app/views/builds/show.html.haml
- jobs_count = @build.jobs.count
- @build.jobs.each_with_index do |job, i|
  = render partial: 'build_jobs/build_job', object: job, locals: {index: i}

  - if i < jobs_count - 1
    %hr