config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }
  # We're only using omniauth for now, so need to add our own signout route
  devise_scope :user do
    delete 'signout(.:format)' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :repos, only: [:index, :show] do
    resources :builds, only: [:index, :show] do
      resources :jobs, controller: :build_jobs, only: :show
    end
  end

  post 'notifications/travis', to: 'notifications#travis'
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Zurb Foundation
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert-box #{name.to_s == 'notice' ? 'success' : 'alert'}", "data-alert" => ""}
      = content_tag :div, msg
      %a.close{:href => "#"} &times;

app/views/layouts/_navigation.html.haml
-# navigation styled for Zurb Foundation 5
-# the syntax for data-topbar may need to change for Zurb Foundation 5
%nav.top-bar{"data-topbar" => true}
  %ul.title-area
    %li.name
      = image_tag "top-bar-logo.png", class: 'logo'

    -# No menu items if user is not signed in
    - if user_signed_in?
      %li.toggle-topbar.menu-icon
        %a{:href => "#"}
          Menu

  .top-bar-section
    %ul.left
      - if user_signed_in?
        - if Repo.count > 1
          %li.has-dropdown
            = link_to 'Repos', repos_path
            %ul.dropdown
              - Repo.all.limit(15).each do |repo|
                %li.repo_link= link_to repo.path, repo

        - if latest_build
          %li= link_to "Latest Build (#{latest_build.repo.name} ##{latest_build.number})", repo_build_path(latest_build.repo, latest_build)

    %ul.right
      - if user_signed_in?
        %li= link_to 'Sign out', destroy_user_session_path, :method=>'delete'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'CI Gallery'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'CI Gallery'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    <link href='//fonts.googleapis.com/css?family=Rambla:400,700' rel='stylesheet' type='text/css'>

    <link rel="icon" sizes="16x16" href="/favicon-16.png">
    <link rel="icon" sizes="32x32" href="/favicon-32.png">
    <link rel="icon" sizes="48x48" href="/favicon-48.png">

    -# Modernizr is required for Zurb Foundation
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield